const STATUS_VI: Record<string, string> = {
  READY: "Sẵn sàng",
  BLOCKED: "Bị chặn",
  OPTIONAL: "Không bắt buộc",
  STARTED: "Đã bắt đầu",
  RUNNING: "Đang chạy",
  QUEUED: "Đang chờ",
  COMPLETED: "Hoàn thành",
  COMPLETE: "Hoàn thành",
  FAILED: "Thất bại",
  PASS: "Đạt",
  WARN: "Cảnh báo",
  FAIL: "Không đạt",
  PENDING: "Đang chờ",
  ACTIVE: "Đang hoạt động",
  INACTIVE: "Không hoạt động",
  PROPOSED: "Đề xuất",
  CANDIDATE: "Ứng viên",
  TESTING: "Đang kiểm chứng",
  SUPPORTED: "Đã có bằng chứng hỗ trợ",
  REJECTED: "Đã bác bỏ",
  INSUFFICIENT_EVIDENCE: "Chưa đủ bằng chứng",
  READY_FOR_REVIEW: "Sẵn sàng để duyệt",
  REQUEST_MORE_EVIDENCE: "Cần thêm bằng chứng",
  NEEDS_MORE_EVIDENCE: "Cần thêm bằng chứng",
  INCONCLUSIVE: "Chưa đủ kết luận",
  VALIDATED: "Đã kiểm chứng",
  REGRESSED: "Thoái lui",
  CONTESTED: "Có tranh luận",
  APPROVE: "Duyệt",
  PROMOTE: "Đưa vào áp dụng",
  KEEP: "Giữ nguyên",
  REJECT: "Bác bỏ",
  ROLLBACK: "Hoàn tác",
  ARCHIVE_CANDIDATE: "Lưu trữ ứng viên",
  CONSISTENT: "Nhất quán",
  INCONSISTENT: "Không nhất quán",
  PUBLISHED: "Đã xuất bản",
  NOT_PUBLISHED: "Chưa xuất bản",
  APPROVED_NOT_PUBLISHED: "Đã duyệt · chưa xuất bản",
  AWAITING_APPROVAL: "Chờ duyệt",
  WAITING_APPROVAL: "Chờ duyệt",
  AWAITING_FOUNDER_APPROVAL: "Chờ Người sáng lập duyệt",
  RECONCILIATION_REQUIRED: "Cần xác nhận hợp nhất",
  ADMITTED: "Có thể tiếp tục",
  MISSING: "Đang thiếu",
  PLANNED: "Đã lên kế hoạch",
  IN_PROGRESS: "Đang sản xuất",
  NEEDS_UPDATE: "Cần cập nhật",
  WEAK: "Nội dung yếu",
  ANSWERED: "Đã trả lời",
  PARTIAL: "Đã có một phần",
  STALE: "Đã cũ",
  COLLISION: "Có xung đột",
  MIXED: "Hỗn hợp",
  ok: "Bình thường",
  pending: "Đang chờ",
  waiting_approval: "Chờ duyệt",
  skipped: "Đã bỏ qua",
  draft: "Bản nháp",
  approved: "Đã duyệt",
  published: "Đã xuất bản",
  superseded: "Đã được thay thế",
  completed: "Hoàn thành",
  failed: "Thất bại",
  running: "Đang chạy",
  queued: "Đang chờ",
  leased: "Đang xử lý",
  cancelled: "Đã hủy",
};

export function uiStatusLabel(value: string): string {
  return STATUS_VI[value] ?? value;
}
